### ISSUE TITLE
No such module 'SmartlookAnalytics'

### ISSUE THREAD

**Issue by coltkenn2658** [nstudio/nativescript-ui-kit#19]
Hi!

### Problem & Triaging
I have been trying to integrate Smartlook into my Nativescript Angular app (ios & android). While there haven't been any issues with android, I haven't been able to set anything up past build time for ios. I initially receive this error during the xcode build after the pods have been installed:

```
/User/my-project/node_modules/@nstudio/nativescript-smartlook/platforms/ios/src/NSCSmartlook.swift:3:8: 
error: no such module 'SmartlookAnalytics'
import SmartlookAnalytics
       ^
```

In attempt to resolve this, I included SmartlookAnalytics in the PodFile:

```
pod 'SmartlookAnalytics'
```

After adding this, I rebuilt the project and was able to confirm the SmartlookAnalytics pod was installed (pod version 0.0.1). This ultimately resolved the 'no such module' error, however, I was then bombarded with a few new errors:

```
error: type 'Smartlook' has no member 'instance'
Smartlook.instance.preferences.projectKey = key
```
```
error: type 'Smartlook' has no member 'instance'
Smartlook.instance.start()
```
```
error: cannot find 'Properties' in scope
let props = Properties()
```
```
error: value of type 'UIView' has no member 'slSensitive'
view.slSensitive = sensitive
```

^This wasn't all the errors, it was just a few of them, but they were all similar to the above. 

I've also attempted to change the package version in `nativescript.config.ts` but it had no effect.

### Versioning
- NS: 8.5.7
- NS iOS: 8.5.2
- NS Types: 8.5.0
- "@nstudio/nativescript-smartlook: 1.0.1
- Swift: 5.7
- analytics-swift-package: 
```
ios: {
    SPMPackages: [
      {
        name: 'SmartlookAnalytics',
        libs: ['SmartlookAnalytics'],
        repositoryURL: 'https://github.com/smartlook/analytics-swift-package.git',
        version: '2.2.4'
      }
    ]
  }
```

Let me know if any additional information is needed. Looking forward to hearing back!

**Comment by NathanWalker** [comment]
Hi @coltkenn2658 ensure only the SPM is added as will only work with SPM and not the pod. Then be sure to run “ns clean” before running again.

**Comment by coltkenn2658** [comment]
@NathanWalker Hi. I removed SmartlookAnalytics from the Podfile, ran `ns clean`, deleted any build folders that were created in DerivedData directory then rebuilt the app with `ns build ios`. Same initial issue: `error: no such module 'SmartlookAnalytics'`

**Comment by coltkenn2658** [comment]
Upgrading the global nativescript version (8.4.0 -> 8.5.3 (latest at the time of this writing)) resolved this issue:

`npm i -g nativescript`
