### ISSUE TITLE
Backgrounds and texts remain translucent with autoStart="false" on Android

### ISSUE THREAD

**Issue by sebj54** [nstudio/nativescript-ui-kit#5]
Hi there!

I've been an early adopter of the shimmer package (I implemented it when it only has iOS support) and I'm currently trying to add shimmer on Android in my app.

Apparently, when you use `autoStart="false"`, backgrounds of `Shimmer`'s children remains translucent even when it is not shimmering. 

I wanted to provide you a way to reproduce based on your demos, but I can't even run the demo:

```
~/p/nativescript-ui-kit/a/demo ~ ns run android
Searching for devices...

changed 1 package, and audited 9 packages in 697ms

found 0 vulnerabilities

changed 1 package, and audited 9 packages in 631ms

found 0 vulnerabilities
Preparing project...
/Users/me/.nvm/versions/node/v14.18.1/bin/node: bad option: --config=/Users/me/projets/nativescript-ui-kit/apps/demo/webpack.config.js
/Users/me/.nvm/versions/node/v14.18.1/bin/node: bad option: --env.hmr
/Users/me/.nvm/versions/node/v14.18.1/bin/node: bad option: --env.externals=~/package.json
/Users/me/.nvm/versions/node/v14.18.1/bin/node: bad option: --env.externals=package.json
/Users/me/.nvm/versions/node/v14.18.1/bin/node: bad option: --env.android
/Users/me/.nvm/versions/node/v14.18.1/bin/node: bad option: --env.appPath=src
/Users/me/.nvm/versions/node/v14.18.1/bin/node: bad option: --env.appResourcesPath=../../tools/assets/App_Resources
/Users/me/.nvm/versions/node/v14.18.1/bin/node: bad option: --env.nativescriptLibPath=/Users/me/.nvm/versions/node/v14.18.1/lib/node_modules/nativescript/lib/nativescript-cli-lib.js
/Users/me/.nvm/versions/node/v14.18.1/bin/node: bad option: --env.config=false
/Users/me/.nvm/versions/node/v14.18.1/bin/node: bad option: --env.sourceMap
/Users/me/.nvm/versions/node/v14.18.1/bin/node: bad option: --watch
Executing webpack failed with exit code 9.
```

I also have an error when I run `npm start`:

```
~/p/nativescript-ui-kit ~ npm start

> plugins@0.0.0 start
> nps

sh: nps: command not found
```

Tell me if you need a proper way to reproduce the bug, I'll try to create a demo app.

**Comment by sebj54** [comment]
I still can't buidl demos (I might have missed something), but I managed to make Shimmer component work with `autoStart="false"`. 

I have to call `shimmerNativeView.android.hideShimmer()`  right after the Shimmer's child is loaded. Here is the vue code:

```vue
<template>
    <shimmer :autoStart="false">
        <stack-layout @loaded="handleWrapperLoaded">
            <!-- … -->
        </stack-layout>
    </shimmer>
</template>

<script>
export default {
    methods: {
        handleWrapperLoaded() {
            if (this.$el.nativeView.android) {
                this.$el.nativeView.android.hideShimmer()
            }
        },
    },
}
</script>
```

I can do the PR if you want, I think an `else` statement might do the trick here: https://github.com/nstudio/nativescript-ui-kit/blob/14649657468c329cea17e99d242ade3a31476a37/packages/nativescript-shimmer/index.android.ts#L36-L38

**Comment by NathanWalker** [comment]
Interesting, I wonder if Vue rendering effects things differently - a PR would be appreciated.

On the repo, right after you cloned it, did you: `npm run setup` ?
That installs the dependencies and is the first thing stated in the README: https://github.com/nstudio/nativescript-ui-kit#nstudio-plugins

Additionally it is intended to run everything from the root of the workspace always. `npm start` will display a menu that let's you invoke anything including running demo apps. When choosing options the commands used to run them are also printed so you can run them direct anytime if desired as well, for example: `nx run demo:android`

**Comment by sebj54** [comment]
Thank you, the android demo now runs properly. I think I've missed the `npm run setup` the first time 😕

PR is coming soon :)

I don't know what is the root cause, it may be Vue but also the fact that my app loads several plugins and custom components. The problem is also not present 100% of the time. The only thing I know is that `stopShimmer` does not solve the problem but `hideShimmer` does. So I think it is related to `mShowShimmer`:

https://github.com/nstudio/nativescript-ui-kit/blob/14649657468c329cea17e99d242ade3a31476a37/packages/nativescript-shimmer/platforms/android/java/io/nstudio/ui/Shimmer.java#L797-L801

Maybe `dispatchDraw` is called even if `autoStart` is false?

https://github.com/nstudio/nativescript-ui-kit/blob/14649657468c329cea17e99d242ade3a31476a37/packages/nativescript-shimmer/platforms/android/java/io/nstudio/ui/Shimmer.java#L853-L858

**Comment by sebj54** [comment]
I ran demos and I noticed differences between Android & iOS rendering. I think it is related to the problem I reported.

Here are the views on load:

| Android | iOS |
| -------- | --- |
| ![Screenshot_20220128-182948](https://user-images.githubusercontent.com/5880435/151596130-374eb0a6-668f-4bf5-aa61-bedfb31257b6.png) | ![IMG_0149](https://user-images.githubusercontent.com/5880435/151595378-5182ef63-f7de-49f3-8813-6981afdb58b7.PNG) |

And here are the views when I stopped Shimmer by pressing "Toggle Shimmer":


| Android | iOS |
| -------- | --- |
| ![Screenshot_20220128-183222](https://user-images.githubusercontent.com/5880435/151596544-afaf1abc-0306-4fe3-b94c-3c68cdfef0f9.png) | ![IMG_669CE561EAE2-1](https://user-images.githubusercontent.com/5880435/151595897-bc8e2d8d-e08a-478b-ba82-3a0c8e845162.jpeg) | 

You can notice that it looks "paused" and not stopped on Android, elements are dimmed and you can see the "shimmer light" effect, but it's not moving. 

If it's not the desired effect, I think `stopShimmer` should always be replaced by `hideShimmer` on Android, what do you think?

**Comment by NathanWalker** [comment]
Yes I believe you are correct let's swap them.

**Comment by sebj54** [comment]
Ok, PR incoming!
